apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: syfosmjob
  namespace: syfocron
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: syfosmjob
              image: "docker.pkg.github.com/navikt/syfosmjob:{{tag}}"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "1000m"
                limits:
                  memory: "256Mi"
                  cpu: "1000m"
              volumeMounts:
                - mountPath: /etc/ssl/certs/ca-certificates.crt
                  name: ca-bundle
                  subPath: ca-bundle.pem
                - mountPath: /etc/pki/tls/certs/ca-bundle.crt
                  name: ca-bundle
                  subPath: ca-bundle.pem
                - mountPath: /etc/ssl/ca-bundle.pem
                  name: ca-bundle
                  subPath: ca-bundle.pem
                - mountPath: /etc/pki/tls/cacert.pem
                  name: ca-bundle
                  subPath: ca-bundle.pem
                - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
                  name: ca-bundle
                  subPath: ca-bundle.pem
                - mountPath: /etc/ssl/certs/java/cacerts
                  name: ca-bundle
                  subPath: ca-bundle.jks
                - mountPath: /var/run/secrets/nais.io/vault
                  name: vault-secrets
              env:
                - name: SYFOSMREGISTER_DB_URL
                  value: jdbc:postgresql://fsspgdb.adeo.no:5432/syfosmregister
                - name: MOUNT_PATH_VAULT
                  value: /postgresql/prod-fss
                - name: PROMETHEUS_PUSH_GATEWAY_URL
                  value: "http://nais-prometheus-prometheus-pushgateway.nais:9091"
          initContainers:
            - env:
                - name: VKS_VAULT_ADDR
                  value: https://vault.adeo.no
                - name: VKS_AUTH_PATH
                  value: /kubernetes/prod/fss
                - name: VKS_SECRET_DEST_PATH
                  value: /var/run/secrets/nais.io/vault
              image: navikt/vks:29
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
              name: vks
              volumeMounts:
                - mountPath: /var/run/secrets/nais.io/vault
                  name: vault-secrets
          serviceAccount: podcreator
          serviceAccountName: podcreator
          volumes:
            - configMap:
                defaultMode: 420
                name: ca-bundle
              name: ca-bundle
            - emptyDir:
                medium: Memory
              name: vault-secrets
